openapi: 3.0.0
info:
  title: API de Carritos de Compras
  version: 1.0.0
paths:
  /carts:
    get:
      summary: Obtener todos los carritos de compras
      operationId: getCarts
      responses:
        "200":
          description: Lista de carritos de compras

    post:
      summary: Crear un nuevo carrito de compras
      operationId: createCart
      responses:
        "200":
          description: Carrito de compras creado exitosamente

  /carts/{cid}:
    get:
      summary: Obtener un carrito de compras por ID
      operationId: getCartByID
      parameters:
        - in: path
          name: cid
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Detalles del carrito de compras

    delete:
      summary: Eliminar un carrito de compras por ID
      operationId: deleteCart
      parameters:
        - in: path
          name: cid
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Carrito de compras eliminado exitosamente

  /carts/{cid}/{pid}:
    put:
      summary: Agregar un producto al carrito de compras
      operationId: addProductToCart
      parameters:
        - in: path
          name: cid
          required: true
          schema:
            type: string
        - in: path
          name: pid
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Producto agregado al carrito

  /carts/{cid}/products/{pid}:
    delete:
      summary: Eliminar un producto específico del carrito de compras
      operationId: deleteProductFromCart
      parameters:
        - in: path
          name: cid
          required: true
          schema:
            type: string
        - in: path
          name: pid
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Producto eliminado del carrito

  /carts/{cid}/products:
    delete:
      summary: Eliminar todos los productos del carrito de compras
      operationId: deleteAllProductFromCart
      parameters:
        - in: path
          name: cid
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Todos los productos eliminados del carrito

  /carts/{cid}/purchase:
    post:
      summary: Realizar la compra de productos en el carrito de compras
      operationId: purchaseCart
      parameters:
        - in: path
          name: cid
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Compra realizada con éxito
