openapi: 3.0.0
info:
  title: API de Usuarios
  version: 1.0.0
paths:
  /users:
    get:
      summary: Obtener todos los usuarios
      operationId: getUsers
      responses:
        "200":
          description: Lista de usuarios

  /users/{value}:
    get:
      summary: Obtener un usuario por valor
      operationId: getUser
      parameters:
        - in: path
          name: value
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Detalles del usuario

  /users/{uid}:
    put:
      summary: Modificar un usuario por ID
      operationId: updateUser
      parameters:
        - in: path
          name: uid
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserInput"
      responses:
        "200":
          description: Usuario modificado exitosamente

    delete:
      summary: Eliminar un usuario por ID
      operationId: deleteUser
      parameters:
        - in: path
          name: uid
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Usuario eliminado exitosamente

  /users/premium/{uid}:
    put:
      summary: Actualizar el rol de un usuario a premium
      operationId: roleUser
      parameters:
        - in: path
          name: uid
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Rol de usuario actualizado a premium

  /users/{uid}/documents:
    post:
      summary: Subir documentos para un usuario
      operationId: uploadDocuments
      parameters:
        - in: path
          name: uid
          required: true
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                files:
                  type: array
                  items:
                    type: string
                    format: binary
      responses:
        "200":
          description: Documentos subidos exitosamente

  /users/deleteInactiveUsers:
    delete:
      summary: Eliminar usuarios inactivos
      operationId: deleteInactiveUsers
      responses:
        "200":
          description: Usuarios inactivos eliminados exitosamente

  /users/controller/admin:
    get:
      summary: Vista de administrador para gestionar usuarios
      operationId: adminUsers
      responses:
        "200":
          description: Vista de administrador para gestionar usuarios

components:
  schemas:
    UserInput:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        role:
          type: string
      required:
        - name
        - email
        - role
